import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AuthContextProvider } from '@/contexts/authContext'
import './globals.css'
import { SocketNotification } from '@/components/SocketNotification'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <AuthContextProvider>
          {children}

          <SocketNotification />
        </AuthContextProvider>
      </body>
    </html>
  );
}
